import time
from playwright.sync_api import sync_playwright,expect

with sync_playwright() as p:
    browser=p.chromium.launch(args=['--no-sandbox'])
    for width,height in [(1440,1000),(390,844)]:
        page=browser.new_page(viewport={'width':width,'height':height})
        errors=[]
        page.on('pageerror',lambda e:errors.append(str(e)))
        page.goto('http://browserweb:8000/')
        expect(page).to_have_title('VANTAGE · 모의투자')
        page.locator('#username').fill('browser_'+str(width)+'_'+str(int(time.time())))
        page.locator('#password').fill('abcd1234')
        page.locator('button[value="register"]').click()
        expect(page.locator('#dashboard')).to_be_visible()
        page.locator('a[href="#portfolio"]').click()
        expect(page.locator('#metrics')).to_contain_text('100,000')
        page.locator('a[href="#fx"]').click()
        expect(page.locator('#fxRate')).to_contain_text('1 USD')
        expect(page.locator('#fxAmountUnit')).to_have_text('USD')
        expect(page.locator('#fxAvailable')).to_contain_text('100,000')
        page.locator('#fxAmount').fill('1000')
        page.locator('#fxPreview').click()
        expect(page.locator('#fxEstimate')).to_contain_text('998,500')
        page.locator('#fxForm button.full-width').click()
        expect(page.locator('#fxHistory')).to_contain_text('998,500')
        expect(page.locator('#fxAvailable')).to_contain_text('99,000')
        page.locator('#fxSource').select_option('KRW')
        expect(page.locator('#fxAmountUnit')).to_have_text('KRW')
        expect(page.locator('#fxAvailable')).to_contain_text('998,500')
        page.locator('a[href="#explore"]').click()
        expect(page.locator('#exploreMarkets button')).to_have_count(5)
        expect(page.locator('#exploreRows th')).to_contain_text(['#','종목','현재가','등락률','거래대금','거래량','시장'])
        expect(page.locator('#exploreRows .admin-diagnostic')).to_have_count(0)
        page.locator('[data-asset="us_bond"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('미국 국채 20년')
        page.locator('[data-asset="gold"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('SPDR Gold Shares')
        expect(page.locator('#exploreRows')).to_contain_text('ACE KRX금현물')
        expect(page.locator('#exploreRows td.gain').first).to_have_css('color','rgb(217, 75, 87)')
        expect(page.locator('#exploreRows td.loss').first).to_have_css('color','rgb(54, 122, 231)')
        page.locator('#displayCurrency').select_option('KRW')
        expect(page.locator('#exploreFxNote')).to_contain_text('기준환율')
        expect(page.locator('#exploreRows')).to_contain_text('₩100,000')
        page.locator('[data-asset="kr_bond"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('Kodex 국고채3년')
        expect(page.locator('#exploreRows')).to_contain_text('억원')
        page.locator('[data-asset="kr"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('삼성전자')
        page.locator('[data-asset="us"]').click()
        expect(page.locator('[data-asset="us"]')).to_have_attribute('aria-pressed','true')
        expect(page.locator('#exploreNotice')).to_contain_text('순위가 아닙니다')
        expect(page.locator('#exploreRows')).to_contain_text('Apple')
        page.locator('[data-kind="up"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('Apple')
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth+1')
        if width<600: expect(page.locator('#exploreRows .volume-cell').last).to_be_visible()
        page.screenshot(path=f'/artifacts/explore-{width}.png',full_page=True)
        page.locator('#exploreRows .stock-link').first.click()
        expect(page.locator('#detailPrice')).to_contain_text('100')
        expect(page.locator('#detailPrice .gain').first).to_have_css('color','rgb(217, 75, 87)')
        expect(page.locator('#orderType')).to_have_count(0)
        expect(page.locator('#searchResults')).to_contain_text('최근 본 종목')
        expect(page.locator('#searchResults')).to_contain_text('AAPL')
        expect(page.locator('#chartNotice')).to_contain_text('과거 가격 데이터')
        expect(page.locator('#periodPerformance')).to_contain_text('%')
        page.locator('#displayCurrency').select_option('USD')
        expect(page.locator('#displayCurrency')).to_have_value('USD')
        expect(page.locator('#detailPrice')).to_contain_text('US$100')
        expect(page.locator('#periodPerformance')).to_contain_text('US$100.00')
        expect(page.locator('#orderEstimate')).to_contain_text('US$')
        page.locator('#displayCurrency').select_option('KRW')
        expect(page.locator('#detailPrice')).to_contain_text('₩100,000')
        expect(page.locator('#periodPerformance')).to_contain_text('₩100,000')
        expect(page.locator('#orderEstimate')).to_contain_text('₩')
        for period in ['1D','1W','3M','1Y','5Y','ALL']:
            page.locator(f'[data-range="{period}"]').click()
            expect(page.locator('#chartNotice')).to_contain_text('과거 가격 데이터')
            expect(page.locator('#periodPerformance')).to_contain_text(period+' ·')
            expect(page.locator('#periodPerformance')).to_contain_text('₩5,900')
        page.locator('#priceChart').focus();page.keyboard.press('ArrowRight')
        expect(page.locator('#chartTooltip')).to_contain_text('구간 시작 대비')
        page.locator('[data-order-share="0.05"]').click()
        expect(page.locator('#quantity')).to_have_value('49')
        expect(page.locator('#orderEstimate')).to_contain_text('수수료')
        page.locator('#quantity').fill('2')
        page.locator('#submitOrder').click()
        expect(page.locator('#status')).to_contain_text('체결')
        expect(page.locator('#orderEstimate')).to_contain_text('보유 주식2주')
        page.locator('#side').select_option('sell')
        page.locator('[data-order-share="0.05"]').click()
        expect(page.locator('#quantity')).to_have_value('0')
        expect(page.locator('#submitOrder')).to_be_disabled()
        page.locator('[data-order-share="0.5"]').click()
        expect(page.locator('#quantity')).to_have_value('1')
        expect(page.locator('#submitOrder')).to_be_enabled()
        page.locator('#watchAdd').click()
        expect(page.locator('#status')).to_contain_text('관심종목')
        page.screenshot(path=f'/artifacts/detail-{width}.png',full_page=True)
        page.locator('a[href="#watchlist"]').click()
        expect(page.locator('#watchRows .watch-name')).to_contain_text('Apple')
        expect(page.locator('#watchRows .watch-price')).to_contain_text('₩100,000')
        expect(page.locator('#watchRows .watch-change .gain').first).to_have_css('color','rgb(217, 75, 87)')
        page.screenshot(path=f'/artifacts/watchlist-{width}.png',full_page=True)
        page.locator('a[href="#portfolio"]').click()
        expect(page.locator('#positions')).to_contain_text('AAPL')
        expect(page.locator('#positions .portfolio-stock-link')).to_have_attribute('href','#detail/AAPL')
        page.screenshot(path=f'/artifacts/portfolio-{width}.png',full_page=True)
        page.locator('#positions .portfolio-stock-link').click()
        expect(page.locator('#detailTitle')).to_contain_text('Apple')
        page.locator('.app-nav a[href="#ranking"]').click()
        expect(page.locator('#rankingStatus')).to_contain_text('10초 단위')
        with page.expect_response(lambda r:r.url.endswith('/api/ranking'),timeout=15000):
            pass
        expect(page.locator('#ranking .user-link').first).to_have_css('font-size','18px' if width<600 else '19px')
        rows_before=page.locator('#ranking').inner_text()
        page.route('**/api/ranking',lambda route:route.fulfill(status=503,json={'detail':'test outage'}))
        page.evaluate('refreshRankingOnly()')
        expect(page.locator('#rankingStatus')).to_contain_text('마지막 정상 갱신')
        assert page.locator('#ranking').inner_text()==rows_before
        page.unroute('**/api/ranking')
        page.locator('#ranking .user-link').first.click()
        expect(page.locator('#publicTitle')).to_contain_text('포트폴리오')
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth+1'), 'page overflows viewport'
        assert not errors,errors
        page.close()
    page=browser.new_page(viewport={'width':390,'height':844})
    page.goto('http://browserweb:8000/')
    page.locator('#username').fill('browser_admin')
    page.locator('#password').fill('browser-fixture-password')
    page.locator('button[value="login"]').click()
    expect(page.locator('#adminNav')).to_be_visible()
    expect(page.locator('[data-page="admin"]')).to_be_visible()
    expect(page.locator('#adminOverview')).to_contain_text('사용자')
    expect(page.locator('.app-nav a:visible')).to_have_count(1)
    page.locator('#adminTargetSearch').fill('browser_admin')
    expect(page.locator('#adminTarget option')).to_have_count(2)
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth+1')
    page.screenshot(path='/artifacts/explore-admin-390.png',full_page=True)
    page.close()
    browser.close()
print('Desktop + mobile browser flows passed: registration, FX, charts, buy, watchlist, portfolio')
