import re,time,zlib,struct
from playwright.sync_api import sync_playwright,expect

def png(width=64,height=64):
    """Left half red, right half blue, so a crop position can be checked."""
    raw=b''.join(b'\x00'+b''.join(bytes([220,30,30] if x<width//2 else [30,30,220]) for x in range(width)) for _ in range(height))
    chunk=lambda kind,data:struct.pack('>I',len(data))+kind+data+struct.pack('>I',zlib.crc32(kind+data))
    return b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',width,height,8,2,0,0,0))+chunk(b'IDAT',zlib.compress(raw))+chunk(b'IEND',b'')

with sync_playwright() as p:
    browser=p.chromium.launch(args=['--no-sandbox'])
    # This run's own second account: the ranking step opens another user's public
    # profile, and must not depend on accounts left behind by earlier runs.
    peer='peer_'+str(int(time.time()))
    setup=p.request.new_context(base_url='http://browserweb:8000')
    csrf=setup.get('/api/session').json()['csrf']
    assert setup.post('/api/register',headers={'x-csrf-token':csrf},data={'username':peer,'password':'abcd1234','password_confirm':'abcd1234'}).ok
    setup.dispose()
    for width,height in [(1440,1000),(390,844)]:
        page=browser.new_page(viewport={'width':width,'height':height})
        errors=[]
        page.on('pageerror',lambda e:errors.append(str(e)))
        page.goto('http://browserweb:8000/')
        expect(page).to_have_title('ALPHARENA · 모의투자')
        expect(page.locator('header .brand-logo')).to_have_attribute('alt','ALPHARENA')
        name='browser_'+str(width)+'_'+str(int(time.time()))
        page.locator('#showSignup').click()
        expect(page.locator('#registerForm')).to_be_visible()
        page.locator('#registerUsername').fill(name)
        page.locator('#registerPassword').fill('abcd1234')
        page.locator('#registerConfirm').fill('abcd1235')
        page.locator('#registerSubmit').click()
        expect(page.locator('#registerError')).to_have_text('비밀번호가 일치하지 않습니다.')
        page.locator('#registerConfirm').fill('abcd1234')
        page.locator('#registerSubmit').click()
        expect(page.locator('#authForm')).to_be_visible()
        expect(page.locator('#toasts')).to_contain_text('회원가입이 완료')
        expect(page.locator('#username')).to_have_value(name)
        page.locator('#password').fill('abcd1234')
        page.locator('#loginSubmit').click()
        expect(page.locator('#dashboard')).to_be_visible()
        page.locator('a[href="#portfolio"]').click()
        expect(page.locator('#metrics')).to_contain_text('100,000')
        page.locator('a[href="#fx"]').click()
        expect(page.locator('#fxRate')).to_contain_text('1 USD')
        expect(page.locator('#fxAmountUnit')).to_have_text('USD')
        expect(page.locator('#fxAvailable')).to_contain_text('100,000')
        page.locator('#fxAmount').fill('1000')
        page.locator('#fxPreview').click()
        expect(page.locator('#fxEstimate')).to_contain_text('998,500')
        page.locator('#fxForm button.full-width').click()
        expect(page.locator('#fxHistory')).to_contain_text('998,500')
        page.screenshot(path=f'/artifacts/fx-{width}.png',full_page=True)
        expect(page.locator('#fxAvailable')).to_contain_text('99,000')
        page.locator('#fxSource').select_option('KRW')
        expect(page.locator('#fxAmountUnit')).to_have_text('KRW')
        expect(page.locator('#fxAvailable')).to_contain_text('998,500')
        page.locator('[data-fx-share="50"]').click()
        expect(page.locator('#fxAmount')).to_have_value('499250')
        expect(page.locator('#fxEstimate')).to_contain_text('최종 수령')
        page.locator('#fxSource').select_option('USD')
        page.locator('[data-fx-share="100"]').click()
        expect(page.locator('#fxAmount')).to_have_value('99000')
        page.locator('a[href="#explore"]').click()
        expect(page.locator('#exploreMarkets button')).to_have_count(5)
        expect(page.locator('#exploreKinds button')).to_have_text(['거래량','거래대금','급상승','급하락','ALPHARENA 인기'])
        expect(page.locator('[data-kind="shares"]')).to_have_attribute('aria-pressed','true')
        page.locator('[data-kind="volume"]').click()
        expect(page.locator('#exploreRows th')).to_contain_text(['#','종목','현재가','등락률','거래대금','거래량','시장'])
        expect(page.locator('#exploreRows .admin-diagnostic')).to_have_count(0)
        page.locator('[data-asset="us_bond"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('미국 국채 20년')
        page.locator('[data-asset="gold"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('SPDR Gold Shares')
        expect(page.locator('#exploreRows')).to_contain_text('ACE KRX금현물')
        expect(page.locator('#exploreRows td.gain').first).to_have_css('color','rgb(217, 75, 87)')
        expect(page.locator('#exploreRows td.loss').first).to_have_css('color','rgb(54, 122, 231)')
        page.locator('#displayCurrency').select_option('KRW')
        expect(page.locator('#exploreFxNote')).to_contain_text('기준환율')
        expect(page.locator('#exploreRows')).to_contain_text('100,000원')
        page.locator('[data-asset="kr_bond"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('Kodex 국고채3년')
        expect(page.locator('#exploreRows')).to_contain_text('억원')
        page.locator('[data-asset="kr"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('삼성전자')
        page.locator('[data-asset="us"]').click()
        expect(page.locator('[data-asset="us"]')).to_have_attribute('aria-pressed','true')
        expect(page.locator('#exploreNotice')).to_contain_text('순위가 아닙니다')
        expect(page.locator('#exploreRows')).to_contain_text('Apple')
        page.locator('[data-kind="up"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('Apple')
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth+1')
        if width<600: expect(page.locator('#exploreRows .volume-cell').last).to_be_visible()
        page.screenshot(path=f'/artifacts/explore-{width}.png',full_page=True)
        page.locator('#exploreRows .stock-link').first.click()
        expect(page.locator('#detailPrice')).to_contain_text('100')
        expect(page.locator('#detailPrice .gain').first).to_have_css('color','rgb(217, 75, 87)')
        expect(page.locator('#orderType')).to_have_count(0)
        expect(page.locator('#searchResults')).to_contain_text('최근 본 종목')
        expect(page.locator('#searchResults')).to_contain_text('AAPL')
        expect(page.locator('#chartNotice')).to_contain_text('과거 가격 데이터')
        expect(page.locator('#periodPerformance')).to_contain_text('%')
        page.locator('#displayCurrency').select_option('USD')
        expect(page.locator('#displayCurrency')).to_have_value('USD')
        expect(page.locator('#detailPrice')).to_contain_text('$100')
        expect(page.locator('#periodPerformance')).to_contain_text('$106.90')
        expect(page.locator('#orderEstimate')).to_contain_text('$')
        page.locator('#displayCurrency').select_option('KRW')
        expect(page.locator('#detailPrice')).to_contain_text('100,000원')
        expect(page.locator('#periodPerformance')).to_contain_text('106,900원')
        expect(page.locator('#orderEstimate')).to_contain_text('원')
        for period in ['1D','1W','3M','1Y','5Y','ALL']:
            page.locator(f'[data-range="{period}"]').click()
            expect(page.locator('#chartNotice')).to_contain_text('과거 가격 데이터')
            expect(page.locator('#periodPerformance')).to_contain_text(period+' ·')
            expect(page.locator('#periodPerformance')).to_contain_text('5,900원')
        page.locator('#priceChart').focus();page.keyboard.press('ArrowRight')
        expect(page.locator('#chartTooltip')).to_contain_text('구간 시작 대비')
        page.locator('[data-order-share="0.05"]').click()
        expect(page.locator('#quantity')).to_have_value('49')
        expect(page.locator('#orderEstimate')).to_contain_text('수수료')
        expect(page.locator('.side-toggle [data-side="buy"]')).to_have_css('color','rgb(217, 75, 87)')
        expect(page.locator('#submitOrder')).to_have_css('background-color','rgb(217, 75, 87)')
        page.locator('#quantity').fill('2')
        page.locator('#submitOrder').click()
        expect(page.locator('#toasts')).to_contain_text('매수 주문이 체결되었습니다.')
        expect(page.locator('#toasts')).to_contain_text('Apple 2주')
        expect(page.locator('#toasts .toast').last).to_be_in_viewport()
        expect(page.locator('#orderEstimate')).to_contain_text('보유 주식2주')
        page.locator('.side-toggle [data-side="sell"]').click()
        expect(page.locator('#side')).to_have_value('sell')
        expect(page.locator('.side-toggle [data-side="sell"]')).to_have_css('color','rgb(54, 122, 231)')
        expect(page.locator('#submitOrder')).to_have_text('매도 주문')
        page.locator('[data-order-share="0.05"]').click()
        expect(page.locator('#quantity')).to_have_value('0')
        expect(page.locator('#submitOrder')).to_be_disabled()
        page.locator('[data-order-share="0.5"]').click()
        expect(page.locator('#quantity')).to_have_value('1')
        expect(page.locator('#submitOrder')).to_be_enabled()
        # 자산 분류 is gone from the order panel.
        expect(page.locator('#category')).to_have_count(0)
        # Reservation: buy 1 share if the price comes down to today's price or lower, then cancel it.
        page.locator('.order-mode [data-mode="reserve"]').click()
        expect(page.locator('#reserveFields')).to_be_visible()
        expect(page.locator('#submitOrder')).to_have_text('예약 매도 등록')
        page.locator('.side-toggle [data-side="buy"]').click()
        expect(page.locator('#submitOrder')).to_have_text('예약 매수 등록')
        expect(page.locator('#reserveTrigger option')).to_have_text(['가격 이하일 때 매수 (지정가)','가격 이상일 때 매수 (돌파)'])
        page.locator('#reserveUseCurrent').click()
        expect(page.locator('#reservePrice')).not_to_have_value('')
        page.locator('#quantity').fill('1')
        expect(page.locator('#submitOrder')).to_be_enabled()
        page.locator('#submitOrder').click()
        expect(page.locator('#toasts')).to_contain_text('예약 매수를 등록했습니다.')
        expect(page.locator('#reserveSymbolRows')).to_contain_text('이하이면 매수 · 1주')
        page.screenshot(path=f'/artifacts/reserve-{width}.png',full_page=True)
        page.locator('#reserveSymbolRows button').first.click()
        expect(page.locator('#toasts')).to_contain_text('예약 주문을 취소했습니다.')
        expect(page.locator('#reserveSymbol')).to_be_hidden()
        page.locator('.order-mode [data-mode="now"]').click()
        expect(page.locator('#reserveFields')).to_be_hidden()
        page.locator('.side-toggle [data-side="sell"]').click()
        expect(page.locator('#submitOrder')).to_have_text('매도 주문')
        page.locator('#watchAdd').click()
        expect(page.locator('#toasts')).to_contain_text('관심종목')
        expect(page.locator('#companyInfo')).to_contain_text('배당률')
        # Wide screens: company info right under the chart, beside the order panel. Phones: after the order panel.
        chart_box,order_box,company_box=(page.locator(s).bounding_box() for s in ('.chart-panel','.order-panel','.company-panel'))
        if width>=900: assert abs(company_box['x']-chart_box['x'])<2 and company_box['y']<order_box['y']+order_box['height'], (chart_box,order_box,company_box)
        else: assert company_box['y']>order_box['y']+order_box['height']-1 and order_box['y']>chart_box['y'], (chart_box,order_box,company_box)
        page.screenshot(path=f'/artifacts/detail-{width}.png',full_page=True)
        page.locator('a[href="#watchlist"]').click()
        expect(page.locator('#watchRows .watch-name')).to_contain_text('Apple')
        expect(page.locator('#watchRows .watch-price')).to_contain_text('100,000원')
        expect(page.locator('#watchRows .watch-change .gain').first).to_have_css('color','rgb(217, 75, 87)')
        page.screenshot(path=f'/artifacts/watchlist-{width}.png',full_page=True)
        page.locator('a[href="#portfolio"]').click()
        expect(page.locator('#positions')).to_contain_text('AAPL')
        expect(page.locator('#myProfile .profile-name')).to_have_text(name)
        expect(page.locator('#myProfile .member-days')).to_contain_text('가입 기간')
        expect(page.locator('#myProfile .member-days dd')).to_have_text('1일')
        expect(page.locator('.app-nav a:visible')).to_have_text(['시장 탐색','포트폴리오','관심종목','랭킹','환전','거래내역'])
        expect(page.locator('#myProfile .avatar')).to_have_attribute('src','/static/avatar-default.svg')
        expect(page.locator('#allocation .allocation-segment')).to_have_count(2)
        expect(page.locator('#allocation .allocation-legend')).to_contain_text('현금')
        page.locator('#displayCurrency').select_option('USD')
        expect(page.locator('#metrics')).to_contain_text('KRW: 998,500원')
        expect(page.locator('#myProfile .profile-stats')).to_contain_text('$')
        page.locator('#displayCurrency').select_option('KRW')
        expect(page.locator('#metrics')).to_contain_text('USD: $')
        for text in (page.locator('#metrics').inner_text(),page.locator('#allocation').inner_text(),page.locator('#positions').inner_text()):
            assert 'US$' not in text and '₩' not in text, text
        assert re.search(r'USD: \$[0-9,]+\.[0-9]{2}',page.locator('#metrics').inner_text()) and re.search(r'KRW: [0-9,]+원',page.locator('#metrics').inner_text())
        expect(page.locator('#myProfile .profile-stats')).to_contain_text('원')
        page.locator('#myProfile').get_by_text('소개 수정').click()
        page.locator('#bioInput').fill('장기 투자 위주로 하고 있습니다.')
        page.locator('#myProfile').get_by_text('소개 저장').click()
        expect(page.locator('#myProfile .profile-bio')).to_have_text('장기 투자 위주로 하고 있습니다.')
        page.locator('#profileImageInput').set_input_files({'name':'avatar.png','mimeType':'image/png','buffer':png(200,100)})
        expect(page.locator('#cropDialog')).to_be_visible()
        page.locator('#cropCancel').click()
        expect(page.locator('#cropDialog')).to_be_hidden()
        expect(page.locator('#myProfile .avatar')).to_have_attribute('src','/static/avatar-default.svg')
        page.locator('#profileImageInput').set_input_files({'name':'avatar.png','mimeType':'image/png','buffer':png(200,100)})
        box=page.locator('#cropCanvas').bounding_box()
        # The wide image covers the square; dragging left brings its right (blue) half into the frame.
        page.mouse.move(box['x']+box['width']*.75,box['y']+box['height']/2);page.mouse.down()
        page.mouse.move(box['x']+box['width']*.25,box['y']+box['height']/2,steps=8);page.mouse.up()
        page.locator('#cropApply').click()
        expect(page.locator('#cropDialog')).to_be_hidden()
        expect(page.locator('#myProfile .avatar')).to_have_attribute('src',f'/api/users/{name}/avatar?v=1')
        # Deleting asks first; cancel keeps the photo, confirm removes it.
        page.locator('#myProfile').get_by_text('사진 삭제').click()
        expect(page.locator('#photoDeleteDialog')).to_contain_text('프로필 사진을 삭제하시겠습니까?')
        page.locator('#photoDeleteCancel').click()
        expect(page.locator('#photoDeleteDialog')).to_be_hidden()
        expect(page.locator('#myProfile .avatar')).to_have_attribute('src',f'/api/users/{name}/avatar?v=1')
        page.locator('#myProfile').get_by_text('사진 삭제').click()
        page.keyboard.press('Escape')
        expect(page.locator('#photoDeleteDialog')).to_be_hidden()
        assert page.evaluate("api('profile').then(p=>p.image_version)")==1
        center=page.evaluate('''async url=>{const b=await createImageBitmap(await (await fetch(url)).blob());const c=document.createElement('canvas');c.width=b.width;c.height=b.height;const x=c.getContext('2d');x.drawImage(b,0,0);return [b.width,[...x.getImageData(b.width/2,b.height/2,1,1).data].slice(0,3)];}''',f'/api/users/{name}/avatar?v=1')
        assert center[0]==512 and center[1][2]>150 and center[1][0]<100, center
        # Zooming out below the frame leaves white margins around the whole photo.
        page.locator('#profileImageInput').set_input_files({'name':'avatar.png','mimeType':'image/png','buffer':png(200,100)})
        for _ in range(6): page.locator('#cropZoomOut').click()
        assert float(page.locator('#cropZoom').input_value())<.5
        # Any zoom the slider or buttons produce is valid; the form never shows a validity message.
        page.locator('#cropZoom').fill('0.4173')
        assert page.evaluate("document.getElementById('cropZoom').validity.valid && document.getElementById('cropForm').checkValidity()")
        page.locator('#cropApply').click()
        expect(page.locator('#myProfile .avatar')).to_have_attribute('src',f'/api/users/{name}/avatar?v=2')
        pixels=page.evaluate('''async url=>{const b=await createImageBitmap(await (await fetch(url)).blob());const c=document.createElement('canvas');c.width=b.width;c.height=b.height;const x=c.getContext('2d');x.drawImage(b,0,0);const at=(px,py)=>[...x.getImageData(px,py,1,1).data].slice(0,3);return {top:at(256,30),center:at(256,256)};}''',f'/api/users/{name}/avatar?v=2')
        assert min(pixels['top'])>235 and min(pixels['center'])<200, pixels
        page.locator('#myProfile').get_by_text('사진 삭제').click()
        page.locator('#photoDeleteConfirm').click()
        expect(page.locator('#photoDeleteDialog')).to_be_hidden()
        expect(page.locator('#myProfile .avatar')).to_have_attribute('src','/static/avatar-default.svg')
        expect(page.locator('#toasts')).to_contain_text('프로필 사진을 삭제했습니다.')
        page.locator('#profileImageInput').set_input_files({'name':'avatar.png','mimeType':'image/png','buffer':b'MZ not a png'})
        expect(page.locator('#toasts')).to_contain_text('올바른 이미지 파일이 아닙니다')
        expect(page.locator('#positions .portfolio-stock-link')).to_have_attribute('href','#detail/AAPL')
        # Account results are valuations, in the basis of the display currency (KRW here).
        expect(page.locator('#metrics small').filter(has_text='평가손익')).to_have_count(1)
        expect(page.locator('#realized')).to_have_count(0)
        # -1,500원 overall: the total value turns blue like the loss itself.
        expect(page.locator('#metrics .metric').first.locator('.loss')).to_have_count(1)
        expect(page.locator('#metrics')).to_contain_text('원화 기준 · 확정 손익 포함')
        expect(page.locator('#metrics')).to_contain_text('달러 기준')
        expect(page.locator('#positions th').nth(5)).to_have_text('평가손익 (원화 기준)')
        expect(page.locator('#positions th').nth(6)).to_have_text('수익률 (원화 기준)')
        # Portfolio order: allocation, holdings, performance, then fees paid per currency.
        order=page.evaluate("[...document.querySelectorAll('section.panel[data-page=portfolio] .section-heading h2')].map(h=>h.textContent)")
        assert order[:4]==['자산 비중','보유 종목','내 성과','수수료'], order
        expect(page.locator('#feeSummary th')).to_have_text(['항목','달러 (USD)','원화 (KRW)'])
        expect(page.locator('#feeSummary .fee-total')).to_contain_text('총 수수료')
        expect(page.locator('#feeRates')).to_contain_text('토스증권 기준')
        # Profile line: tier emblem left of the rank, realized profit; the photo framed in the tier color.
        expect(page.locator('#myProfile .profile-tier .tier-icon')).to_be_visible()
        expect(page.locator('#myProfile')).to_contain_text('실현 손익 (매도 확정)')
        # The photo sits inside the tier emblem's ring.
        expect(page.locator('#myProfile .tier-ring .tier-icon-corner')).to_have_attribute('src',re.compile(r'^/static/tiers/icons/\w+\.svg$'))
        # 수익률 / 수익금 switch on my performance chart.
        page.locator('#myPerformanceMetric [data-metric="pnl"]').click()
        expect(page.locator('#myPerformanceMetric [data-metric="pnl"]')).to_have_attribute('aria-pressed','true')
        page.evaluate("myPerformance.draw({snapshots:[{date:'2026-09-24',cumulative_return_pct:0,pnl_krw:0},{date:'2026-09-25',cumulative_return_pct:1.5,pnl_krw:1500000}]})")
        expect(page.locator('#myPerformanceNotice')).to_contain_text('평가손익 1,500,000원')
        page.locator('#myPerformanceMetric [data-metric="return"]').click()
        expect(page.locator('#myPerformanceNotice')).to_contain_text('평가 수익률 1.50%')
        # My own daily performance chart sits on the portfolio page.
        page.wait_for_function("(t=>t&&!t.includes('조회 중'))(document.getElementById('myPerformanceNotice').textContent)")
        page.screenshot(path=f'/artifacts/portfolio-{width}.png',full_page=True)
        page.locator('#positions .portfolio-stock-link').click()
        expect(page.locator('#detailTitle')).to_contain_text('Apple')
        page.locator('.app-nav a[href="#ranking"]').click()
        expect(page.locator('#rankingStatus')).to_contain_text('10초 단위')
        with page.expect_response(lambda r:r.url.endswith('/api/ranking'),timeout=15000):
            pass
        expect(page.locator('#ranking .user-link').first).to_have_css('font-size','18px' if width<600 else '19px')
        rows_before=page.locator('#ranking').inner_text()
        page.route('**/api/ranking',lambda route:route.fulfill(status=503,json={'detail':'test outage'}))
        # Let an automatic 10-second refresh already in flight finish first.
        page.evaluate('(async()=>{if(rankingRequest)await rankingRequest.catch(()=>{});await refreshRankingOnly();})()')
        expect(page.locator('#rankingStatus')).to_contain_text('마지막 정상 갱신')
        assert page.locator('#ranking').inner_text()==rows_before
        page.unroute('**/api/ranking')
        expect(page.locator('#ranking th')).to_contain_text(['순위','사용자 · 프로필 보기','총 평가금액 (KRW)','평가 수익률 (원화 기준)'])
        expect(page.locator('#ranking td').nth(2)).to_contain_text('원')
        expect(page.locator('#ranking tbody tr').first).to_have_class(re.compile(r'\btop-rank-1\b'))
        expect(page.locator('#ranking tbody tr').first.locator('.tier-icon')).to_have_attribute('src','/static/tiers/icons/master.svg')
        expect(page.locator('#ranking tbody tr').first.locator('.user-link')).to_have_css('color','rgb(148, 51, 224)')
        expect(page.locator('#ranking tbody tr').first).not_to_have_css('background-image','none')
        # The daily arrow: rendered from the row's morning place.
        page.evaluate("rankingCache={...rankingCache,rows:rankingCache.rows.map((r,i)=>i===0?{...r,previous_rank:3}:i===1?{...r,previous_rank:1}:r)};renderRanking()")
        expect(page.locator('#ranking tbody tr').first.locator('.rank-arrow.up')).to_have_text('▲')
        expect(page.locator('#ranking tbody tr').first.locator('.rank-change')).to_have_text('▲2')
        expect(page.locator('#ranking tbody tr').nth(1).locator('.rank-arrow.down')).to_have_css('color','rgb(217, 75, 87)')
        expect(page.locator('#ranking tbody tr .rank-medal svg')).to_have_count(min(3,page.locator('#ranking tbody tr').count()))
        expect(page.locator('#ranking tbody tr').first.locator('.rank-medal')).to_have_attribute('aria-label','1위')
        # Every account in the fixture is even or down, so the total is default ink or blue, never red.
        expect(page.locator('#ranking td:nth-child(3) .gain')).to_have_count(0)
        expect(page.locator('#marketSessions .session-dot').first).to_be_visible()
        page.screenshot(path=f'/artifacts/ranking-{width}.png',full_page=True)
        page.locator('#displayCurrency').select_option('USD')
        expect(page.locator('#ranking th').nth(2)).to_have_text('총 평가금액 (USD)')
        expect(page.locator('#ranking th').nth(3)).to_have_text('평가 수익률 (달러 기준)')
        expect(page.locator('#ranking td').nth(2)).to_contain_text('$')
        page.locator('#displayCurrency').select_option('KRW')
        other=page.locator('#ranking .user-link').filter(has_text=peer).first
        other_name=other.inner_text()
        other.click()
        expect(page.locator('#publicTitle')).to_contain_text(other_name+'님의 투자 현황')
        expect(page.locator('#publicProfile .profile-name')).to_have_text(other_name)
        expect(page.locator('#publicProfile .member-days')).to_contain_text('가입 기간')
        expect(page.locator('#publicProfile .member-days dd')).to_have_text(re.compile(r'^[0-9,]+일$'))
        expect(page.locator('#publicProfile')).not_to_contain_text('소개 수정')
        expect(page.locator('#publicProfile')).not_to_contain_text('사진 변경')
        expect(page.locator('#publicAllocation .allocation-legend')).to_be_visible()
        # The long return explanation was removed; the cards speak for themselves.
        expect(page.locator('#publicReturns')).to_have_count(0)
        page.wait_for_function("!document.getElementById('performanceNotice').textContent.includes('조회 중')")
        # No invented history; one real observation must still be visible.
        page.evaluate('drawPerformance({snapshots:[]})')
        expect(page.locator('#performanceChart')).not_to_be_visible()
        page.evaluate("drawPerformance({snapshots:[{date:'2026-09-25',cumulative_return_pct:-1.02}]})")
        expect(page.locator('#performanceChart')).to_be_visible()
        expect(page.locator('#performanceNotice')).to_contain_text('첫 기록을 점으로')
        expect(page.locator('#performanceChart')).to_have_attribute('aria-label',re.compile('1일 기록'))
        def chart_fits():
            return page.evaluate("""() => {const c=document.getElementById('performanceChart'),p=c.parentElement;
              return c.clientWidth>p.clientWidth-60 && c.clientWidth<=p.clientWidth &&
                c.width===Math.round(c.clientWidth*Math.min(devicePixelRatio||1,2)) &&
                c.height===Math.round(c.clientHeight*Math.min(devicePixelRatio||1,2)) &&
                c.getContext('2d').getImageData(0,0,c.width,c.height).data.some((v,i)=>i%4===3&&v>0); }""")
        assert chart_fits()
        page.screenshot(path=f'/artifacts/performance-single-{width}.png',full_page=True)
        page.evaluate("drawPerformance({snapshots:[{date:'2026-09-24',cumulative_return_pct:0},{date:'2026-09-25',cumulative_return_pct:-1.02},{date:'2026-09-28',cumulative_return_pct:.5}],period_return_pct:.5})")
        page.set_viewport_size({'width':1000 if width==1440 else 430,'height':height})
        page.wait_for_function("Math.abs(document.getElementById('performanceChart').width-document.getElementById('performanceChart').clientWidth*Math.min(devicePixelRatio||1,2))<1")
        assert chart_fits()
        expect(page.locator('#performanceNotice')).to_contain_text('기간 수익률 0.50%')
        page.set_viewport_size({'width':width,'height':height})
        page.wait_for_function("Math.abs(document.getElementById('performanceChart').width-document.getElementById('performanceChart').clientWidth*Math.min(devicePixelRatio||1,2))<1")
        assert chart_fits()
        page.screenshot(path=f'/artifacts/performance-multi-{width}.png',full_page=True)
        # Transfers were removed: no menu entry, and an old link falls back to 시장 탐색.
        expect(page.locator('a[href="#transfer"]')).to_have_count(0)
        page.goto('http://browserweb:8000/#transfer')
        expect(page.locator('[data-page="explore"]')).to_be_visible()
        # History: buy in red, sell in blue; side chips and the month picker filter on the server.
        page.evaluate("api('orders',{symbol:'AAPL',side:'sell',quantity:1,request_id:uuid()})")
        page.goto('http://browserweb:8000/#history')
        expect(page.locator('#history .trade-side.gain').first).to_have_text('매수')
        expect(page.locator('#history .trade-side.gain').first).to_have_css('color','rgb(217, 75, 87)')
        expect(page.locator('#history .trade-side.loss').first).to_have_text('매도')
        page.locator('#historySide button[data-side="sell"]').click()
        expect(page.locator('#history .trade-side.gain')).to_have_count(0)
        expect(page.locator('#history .trade-side.loss').first).to_be_visible()
        assert page.locator('#historyMonth option').count()>=2 and '년' in page.locator('#historyMonth option').nth(1).inner_text()
        page.locator('#historyMonth').select_option(index=1)
        expect(page.locator('#history .trade-side.loss').first).to_be_visible()
        page.screenshot(path=f'/artifacts/history-{width}.png',full_page=True)
        page.locator('#historySide button[data-side=""]').click();page.locator('#historyMonth').select_option('')
        # The rate note is just the date and the rate.
        expect(page.locator('#displayRateNote')).to_have_text(re.compile(r'^\d{4}-\d{2}-\d{2} 기준 · 1 USD = [\d,.]+ KRW$'))
        # Every page follows one amount format: "$1,000.00" and "1,000원".
        for display in ('native','KRW','USD'):
            page.locator('#displayCurrency').select_option(display)
            for hash_ in ('#explore','#portfolio','#history','#fx','#watchlist','#ranking','#detail/AAPL'):
                page.goto('http://browserweb:8000/'+hash_);page.wait_for_load_state('networkidle')
                text=page.locator('main').inner_text()
                assert 'US$' not in text and '₩' not in text, (display,hash_,[l for l in text.splitlines() if 'US$' in l or '₩' in l][:3])
        page.locator('#displayCurrency').select_option('KRW')
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth+1'), 'page overflows viewport'
        assert not errors,errors
        page.close()
    page=browser.new_page(viewport={'width':390,'height':844})
    page.goto('http://browserweb:8000/')
    page.locator('#username').fill('browser_admin')
    page.locator('#password').fill('browser-fixture-password')
    page.locator('#loginSubmit').click()
    expect(page.locator('#adminNav')).to_be_visible()
    expect(page.locator('[data-page="admin"]')).to_be_visible()
    expect(page.locator('#adminOverview')).to_contain_text('사용자')
    expect(page.locator('.app-nav a:visible')).to_have_count(1)
    page.locator('#adminTargetSearch').fill(name)
    expect(page.locator('.admin-result')).to_have_count(1)
    page.locator('.admin-result').click()
    page.locator('#adminNote').fill('홍길동 / 컴공 동기')
    page.locator('#adminNoteForm button').click()
    expect(page.locator('#toasts')).to_contain_text('메모를 저장했습니다')
    page.locator('#adminTargetSearch').fill('컴공')
    expect(page.locator('.admin-result')).to_contain_text(name)
    page.locator('.admin-result').first.click()
    page.locator('[data-admin-action="rebase"]').click()
    expect(page.locator('#adminResult')).to_contain_text('수익률 기준을 현재 평가금액으로 재설정했습니다.')
    page.locator('[data-admin-action="clear"]').click()
    expect(page.locator('#adminResult')).to_contain_text('회원가입 직후 상태로 초기화했습니다.')
    # User list: sortable, 10 per page with numbered page links.
    page.locator('.admin-user-list summary').click()
    expect(page.locator('#adminUsers .admin-user-row').first).to_be_visible()
    assert page.locator('#adminUsers .admin-user-row').count()<=10
    expect(page.locator('#adminUserPages button[aria-current="page"]')).to_have_text('1')
    page.locator('#adminUserSort').select_option('name-asc')
    names=page.locator('#adminUsers .admin-user-who strong').all_inner_texts()
    assert names==sorted(names,key=lambda n:n.split(' · ')[0].split(' - ')[0]) or len(names)<2, names
    if page.locator('#adminUserPages button').count()>3:
        page.locator('#adminUserPages button').filter(has_text='2').first.click()
        expect(page.locator('#adminUserPages button[aria-current="page"]')).to_have_text('2')
    expect(page.locator('#noticeKind option')).to_contain_text(['서버 점검 예고','서버 점검 중','서버 점검 완료'])
    page.locator('#adminAmount').fill('500')
    page.locator('#adminGrantForm button').click()
    expect(page.locator('#adminResult')).to_contain_text('지원금을 지급했습니다.')
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth+1')
    page.screenshot(path='/artifacts/explore-admin-390.png',full_page=True)
    # Notices: the maintenance template, then a custom notice; users see a banner and keep trading.
    user=browser.new_page(viewport={'width':390,'height':844})
    user.goto('http://browserweb:8000/')
    user.locator('#showSignup').click()
    user.locator('#registerUsername').fill(name+'_n'); user.locator('#registerPassword').fill('abcd1234'); user.locator('#registerConfirm').fill('abcd1234')
    user.locator('#registerSubmit').click()
    user.locator('#password').fill('abcd1234'); user.locator('#loginSubmit').click()
    expect(user.locator('#dashboard')).to_be_visible()
    expect(user.locator('#siteNotices')).to_be_hidden()
    expect(page.locator('#noticeKind')).to_have_value('maintenance')
    expect(page.locator('#noticeTitle')).to_have_value('서버 점검 예정')
    page.locator('#noticePost').click()
    expect(page.locator('#noticeStatus')).to_contain_text('게시 중 1개')
    expect(page.locator('#noticeList li')).to_contain_text(['서버 점검 예정'])
    expect(page.locator('#siteNotices')).to_be_hidden()
    # No reload and no manual refresh: the open page picks the notice up by itself.
    first=user.locator('#siteNotices .site-notice').first
    expect(first).to_be_visible(timeout=15000)
    expect(first.locator('.notice-new')).to_be_visible()
    expect(first).to_contain_text('서버 점검이 예정되어 있습니다')
    expect(first.locator('.notice-kind')).to_have_text('서버 점검 예고')
    expect(first).to_be_in_viewport()
    # The badge survives the 10-second refresh until the user clicks it.
    user.wait_for_timeout(11000)
    expect(first.locator('.notice-new')).to_be_visible()
    first.click()
    expect(first.locator('.notice-new')).to_be_hidden()
    user.reload(); expect(user.locator('#siteNotices .site-notice')).to_have_count(1)
    expect(user.locator('#siteNotices .notice-new')).to_be_hidden()  # already seen in this browser
    page.locator('#noticeKind').select_option('general')
    expect(page.locator('#noticeTitle')).to_have_value('')
    page.locator('#noticePost').click()
    expect(page.locator('#noticeError')).to_have_text('공지 제목과 내용을 입력하세요.')
    page.locator('#noticeTitle').fill('이벤트 안내')
    page.locator('#noticeBody').fill('이번 주 수익률 1위에게\n가상 지원금을 드립니다.')
    page.locator('#noticePost').click()
    # Both notices stay up, newest first.
    expect(page.locator('#noticeStatus')).to_contain_text('게시 중 2개')
    expect(page.locator('#noticeList li')).to_have_count(2)
    expect(user.locator('#siteNotices .site-notice')).to_have_count(2,timeout=15000)
    newest=user.locator('#siteNotices .site-notice').first
    expect(newest.locator('.notice-title')).to_have_text('이벤트 안내')
    expect(newest.locator('.notice-new')).to_be_visible()
    expect(newest.locator('.notice-body')).to_have_text('이번 주 수익률 1위에게\n가상 지원금을 드립니다.')
    expect(newest.locator('.notice-kind')).to_have_text('일반 공지')
    user.screenshot(path='/artifacts/notice-390.png')
    page.screenshot(path='/artifacts/notice-admin-390.png',full_page=True)
    # Take down just the maintenance notice; the event notice stays.
    page.locator('#noticeList li').filter(has_text='서버 점검 예정').get_by_role('button').click()
    expect(page.locator('#noticeList li')).to_have_count(1)
    expect(user.locator('#siteNotices .site-notice')).to_have_count(1,timeout=15000)
    expect(user.locator('#siteNotices')).to_contain_text('이벤트 안내')
    page.locator('#noticeClear').click()
    expect(page.locator('#noticeStatus')).to_contain_text('게시 중인 공지가 없습니다')
    expect(user.locator('#siteNotices')).to_be_hidden(timeout=15000)
    user.close()
    page.locator('[data-admin-action="delete"]').click()
    expect(page.locator('#adminResult')).to_contain_text('계정을 영구 삭제했습니다.')
    page.close()
    # Self-service withdrawal for the other fixture account.
    page=browser.new_page(viewport={'width':390,'height':844})
    page.goto('http://browserweb:8000/')
    page.locator('#showSignup').click()
    page.locator('#registerUsername').fill(name+'_x'); page.locator('#registerPassword').fill('abcd1234'); page.locator('#registerConfirm').fill('abcd1234')
    page.locator('#registerSubmit').click()
    page.locator('#password').fill('abcd1234'); page.locator('#loginSubmit').click()
    page.locator('a[href="#portfolio"]').click()
    page.locator('#withdrawOpen').click()
    expect(page.locator('#withdrawDialog')).to_contain_text('정말 회원 탈퇴하시겠습니까?')
    page.locator('#withdrawCancel').click()
    expect(page.locator('#withdrawDialog')).to_be_hidden()
    page.locator('#withdrawOpen').click()
    page.locator('#withdrawPassword').fill('wrong-password'); page.locator('#withdrawConfirm').click()
    expect(page.locator('#withdrawError')).to_have_text('비밀번호가 올바르지 않습니다.')
    page.locator('#withdrawPassword').fill('abcd1234'); page.locator('#withdrawConfirm').click()
    expect(page.locator('#authForm')).to_be_visible()
    expect(page.locator('#toasts')).to_contain_text('회원 탈퇴가 완료')
    assert page.evaluate("fetch('/api/portfolio').then(r=>r.status)")==401
    page.locator('#username').fill(name+'_x'); page.locator('#password').fill('abcd1234'); page.locator('#loginSubmit').click()
    # A failed login is an error toast with the server's reason, not the page status line.
    failure=page.locator('#toasts .toast-error')
    expect(failure).to_have_text(re.compile('로그인하지 못했습니다.\\s+사용자 이름 또는 비밀번호가 올바르지 않습니다.'))
    expect(failure).to_have_attribute('role','alert')
    expect(failure).to_be_in_viewport()
    expect(page.locator('#status')).to_have_text('')
    expect(page.locator('#loginSubmit')).to_be_enabled()
    failure.locator('.toast-close').click()
    expect(failure).to_have_count(0)
    page.locator('#username').fill(peer); page.locator('#password').fill('abcd1234'); page.locator('#loginSubmit').click()
    expect(page.locator('#dashboard')).to_be_visible()
    expect(page.locator('#toasts .toast-error')).to_have_count(0)
    page.close()
    # Valuation metrics on the company panel (fixture figures in tests/browser_server.py).
    # Each page is its own client address: the flows above already spent this run's shared market budget.
    for width,height,address in [(1440,1000,'198.51.100.11'),(390,844,'198.51.100.12')]:
        page=browser.new_page(viewport={'width':width,'height':height},extra_http_headers={'x-real-ip':address})
        errors=[]
        page.on('pageerror',lambda e:errors.append(str(e)))
        page.goto('http://browserweb:8000/')
        name=f'value_{width}_'+str(int(time.time()))
        page.evaluate("""async name=>{const s=await api('session');csrf=s.csrf;await api('register',{username:name,password:'abcd1234',password_confirm:'abcd1234'});await api('login',{username:name,password:'abcd1234'});await boot();}""",name)
        items=page.locator('#companyInfo .valuation-item')
        values=items.locator('strong')
        page.evaluate("openStock('AAPL')")
        expect(items.locator('small')).to_have_text(['시가총액','PER','PBR','ROE','PSR'])
        expect(values).to_have_text(['$3.2T','28.4배','7.2배','31.5%','8.6배'])
        expect(page.locator('#companyInfo .valuation')).to_contain_text('Finnhub · PER·ROE·PSR 최근 12개월, PBR 최근 분기 기준')
        expect(page.locator('#companyInfo')).to_contain_text('연 0.45%')   # the existing facts stay
        expect(page.locator('#companyInfo')).to_contain_text('자산 종류')
        page.locator('#displayCurrency').select_option('KRW')
        expect(values.first).to_have_text('3,200.0조원')
        page.locator('#displayCurrency').select_option('native')
        expect(values.first).to_have_text('$3.2T')
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth+1')
        # One snapshot: the quote and chart above may still change the page height.
        grid,*boxes=page.evaluate("[document.querySelector('#companyInfo .valuation-grid'),...document.querySelectorAll('#companyInfo .valuation-item')].map(n=>{const r=n.getBoundingClientRect();return {y:r.y,width:r.width};})")
        if width<600:   # market cap on its own row, then the four ratios two by two
            assert abs(boxes[0]['width']-grid['width'])<2,boxes
            assert boxes[1]['y']==boxes[2]['y']>boxes[0]['y'] and boxes[3]['y']==boxes[4]['y']>boxes[1]['y'],boxes
        else:
            assert len({round(b['y']) for b in boxes})==1,boxes
        page.screenshot(path=f'/artifacts/valuation-{width}.png',full_page=True)
        # A late company answer for the previous symbol never replaces the current one.
        held=[]
        page.route('**/api/company/NVDA',lambda route:held.append(route))
        page.evaluate("openStock('NVDA')")
        expect(items).to_have_count(0)
        for _ in range(50):
            if held:break
            page.wait_for_timeout(100)
        assert held
        page.evaluate("openStock('KR:005930')")
        expect(values).to_have_text(['450.0조원','14.2배','1.3배','9.1%','2.0배'])
        expect(page.locator('#companyInfo .valuation')).to_contain_text('한국투자증권 · 현재가와 2025.12 결산 재무 기준')
        with page.expect_response('**/api/company/NVDA'):
            held[0].continue_()
        page.wait_for_timeout(300)
        expect(page.locator('#detailTitle')).to_contain_text('삼성전자')
        expect(values).to_have_text(['450.0조원','14.2배','1.3배','9.1%','2.0배'])
        page.unroute('**/api/company/NVDA')
        # Partial figures: a loss-making PER and no book data.
        page.evaluate("openStock('NVDA')")
        expect(values).to_have_text(['$125.4B','적자','정보 없음','정보 없음','20.1배'])
        expect(page.locator('#companyInfo .valuation')).to_contain_text('정보 없음으로 표시')
        # ETFs: no financial ratios, and no error.
        page.evaluate("openStock('GLD')")
        expect(values).to_have_text(['정보 없음']*5)
        expect(page.locator('#companyInfo .valuation')).to_contain_text('ETF 등은 재무 지표가 없을 수 있습니다')
        expect(page.locator('#detailPrice')).to_contain_text('100')
        page.evaluate("openStock('KR:114260')")
        expect(values).to_have_text(['5.2조원']+['정보 없음']*4)
        # A provider outage, and a failing company endpoint, leave price, chart and orders working.
        page.evaluate("openStock('MSFT')")
        expect(page.locator('#companyInfo')).to_contain_text('기업 정보를 불러오지 못했습니다')
        expect(values).to_have_text(['정보 없음']*5)
        expect(page.locator('#companyInfo .valuation')).to_contain_text('투자 지표를 불러오지 못했습니다')
        page.route('**/api/company/IAU',lambda route:route.fulfill(status=503,json={'detail':'기업 정보 점검 중입니다.'}))
        for symbol,label in [('MSFT','Microsoft'),('IAU','iShares Gold Trust')]:
            page.evaluate('s=>openStock(s)',symbol)
            if symbol=='IAU':
                expect(page.locator('#companyInfo')).to_have_text('기업 정보 점검 중입니다.')
                expect(items).to_have_count(0)
            expect(page.locator('#detailPrice')).to_contain_text('100')
            expect(page.locator('#chartNotice')).to_contain_text('과거 가격 데이터')
            expect(page.locator('#periodPerformance')).to_contain_text('%')
            page.locator('#quantity').fill('1')
            page.locator('#submitOrder').click()
            expect(page.locator('#toasts .toast').last).to_contain_text('매수 주문이 체결되었습니다.')
            expect(page.locator('#toasts .toast').last).to_contain_text(label)
        assert errors==[],errors
        page.close()
    # Many holdings: every one gets its own segment; a missing price shows as pending, then fills in.
    page=browser.new_page(viewport={'width':1280,'height':900})
    page.goto('http://browserweb:8000/')
    page.locator('#showSignup').click()
    page.locator('#registerUsername').fill(name+'_many'); page.locator('#registerPassword').fill('abcd1234'); page.locator('#registerConfirm').fill('abcd1234')
    page.locator('#registerSubmit').click()
    page.locator('#password').fill('abcd1234'); page.locator('#loginSubmit').click()
    expect(page.locator('#dashboard')).to_be_visible()
    symbols=['AAPL','MSFT','NVDA','QQQ','VOO','IAU','MU','RKLB']
    page.evaluate('''async symbols=>{for(const [i,symbol] of symbols.entries())await api('orders',{symbol,side:'buy',quantity:i+1,request_id:uuid()});}''',symbols)
    state={'first':True}
    def first_without_price(route):
        response=route.fetch();data=response.json()
        if state['first']:
            state['first']=False
            for row in data['positions']:
                if row['symbol']=='MSFT':row['value']=None;row['pnl']=None;row['return_pct']=None
            data['equity']=None;data['errors']=['MSFT: 시세 수집기가 가격을 준비 중입니다. 잠시 후 다시 시도하세요.']
        route.fulfill(response=response,json=data)
    page.route('**/api/portfolio',first_without_price)
    page.evaluate('refresh()')
    page.locator('a[href="#portfolio"]').click()
    expect(page.locator('#allocation .allocation-legend li.pending')).to_contain_text('시세 준비 중')
    expect(page.locator('#allocation .allocation-segment')).to_have_count(8)
    expect(page.locator('#allocation .allocation-segment')).to_have_count(9,timeout=10000)
    expect(page.locator('#allocation .allocation-legend li')).to_have_count(9)
    expect(page.locator('#allocation .allocation-legend li.pending')).to_have_count(0)
    legend=page.locator('#allocation .allocation-legend').inner_text()
    assert '기타' not in legend and all(n in legend for n in ['Apple','현금']), legend
    page.screenshot(path='/artifacts/allocation-many-1280.png',full_page=True)
    page.close()
    # SSE runs only when the fixture enables it; legacy browser suite remains usable.
    page=browser.new_page(viewport={'width':1280,'height':1000})
    page.goto('http://browserweb:8000/')
    if page.request.get('http://browserweb:8000/api/session').json().get('quote_sse_enabled'):
        name='sse_'+str(int(time.time()))
        page.evaluate("""async name=>{const s=await api('session');csrf=s.csrf;await api('register',{username:name,password:'abcd1234',password_confirm:'abcd1234'});await api('login',{username:name,password:'abcd1234'});await boot();}""",name)
        requests=[]
        page.on('request',lambda r:requests.append((time.monotonic(),r.url)))
        page.evaluate("openStock('AAPL')")
        expect(page.locator('#quoteConnection')).to_contain_text('연결됨')
        page.locator('#displayCurrency').select_option('USD')
        expect(page.locator('#detailPrice')).to_contain_text('$100.00')
        page.wait_for_timeout(500)
        baseline={part:sum(part in url for _,url in requests) for part in ['/api/company/','/api/candles/','/api/quote/']}
        latencies=[]
        for price in range(101,121):
            started=time.monotonic()
            assert page.request.post(f'http://browserweb:8000/internal/test-quote/AAPL?price={price}').ok
            expect(page.locator('#detailPrice strong')).to_have_text(f'${price}.00')
            latencies.append((time.monotonic()-started)*1000)
        page.wait_for_timeout(65000)
        for part,count in baseline.items():
            assert sum(part in url for _,url in requests)==count,(part,requests)
        statuses=[stamp for stamp,url in requests if '/api/market-status/AAPL' in url]
        assert len(statuses)>=2 and 55<statuses[1]-statuses[0]<65,statuses
        assert sum('/api/quote/AAPL' in url for _,url in requests)==0
        p95=sorted(latencies)[int(len(latencies)*.95)-1]
        print(f'SSE local Redis store request → Chromium DOM: n={len(latencies)}, p95={p95:.1f}ms',flush=True)
        assert p95<1000
        with open('/artifacts/sse-latency.json','w') as report:
            import json
            json.dump({'samples_ms':latencies,'p95_ms':p95,'scope':'isolated Docker Redis → FastAPI → Chromium DOM; includes injection HTTP round trip'},report)
        page.evaluate("openStock('MSFT');openStock('NVDA')")
        expect(page.locator('#detailTitle')).to_contain_text('NVIDIA')
        expect(page.locator('#detailPrice strong')).to_have_text('$100.00')
        page.request.post('http://browserweb:8000/internal/test-quote/AAPL?price=777')
        page.wait_for_timeout(300)
        expect(page.locator('#detailPrice strong')).to_have_text('$100.00')
        page.context.set_offline(True)
        page.wait_for_timeout(1000)
        page.context.set_offline(False)
        expect(page.locator('#quoteConnection')).to_contain_text('연결됨',timeout=45000)
        page.evaluate("Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))")
        assert page.evaluate('quoteSource===null&&quoteRetry===null')
        page.evaluate("Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))")
        expect(page.locator('#quoteConnection')).to_contain_text('연결됨')
        page.evaluate("openStock('KR:005930')")
        expect(page.locator('#detailTitle')).to_contain_text('삼성전자')
        expect(page.locator('#quoteConnection')).to_contain_text('연결됨')
        page.locator('#logout').click()
        expect(page.locator('#auth')).to_be_visible()
        assert page.evaluate('quoteSource===null&&quoteRetry===null&&marketTimer===null')
    else:
        name='rollback_'+str(int(time.time()))
        page.evaluate("""async name=>{const s=await api('session');csrf=s.csrf;await api('register',{username:name,password:'abcd1234',password_confirm:'abcd1234'});await api('login',{username:name,password:'abcd1234'});await boot();}""",name)
        requests=[]
        page.on('request',lambda r:requests.append(r.url))
        page.evaluate("openStock('AAPL')")
        expect(page.locator('#detailPrice')).to_contain_text('100')
        expect(page.locator('#quoteConnection')).to_contain_text('30초')
        assert page.evaluate('quoteSource===null&&restTimer!==null')
        page.wait_for_timeout(31000)
        assert sum('/api/quote/AAPL' in url for url in requests)==2,requests
        assert not any('/api/market-stream/' in url for url in requests)
        print('SSE flag OFF: one 30s REST timer, no EventSource passed',flush=True)
    page.close()
    # 30 s market-explore refresh, on a fake clock: only for a signed-in user on the explore page.
    page=browser.new_page(viewport={'width':1280,'height':900})
    page.clock.install()
    explore_calls=[]
    page.on('request',lambda r:explore_calls.append(r.url) if '/api/explore' in r.url else None)
    page.goto('http://browserweb:8000/')
    expect(page.locator('#auth')).to_be_visible()
    page.clock.run_for(95000)
    page.wait_for_timeout(300)
    assert explore_calls==[],explore_calls   # signed out: the login-only API is never polled
    name='refresh_'+str(int(time.time()))
    with page.expect_response(lambda r:'/api/explore' in r.url):
        page.evaluate("""async name=>{const s=await api('session');csrf=s.csrf;await api('register',{username:name,password:'abcd1234',password_confirm:'abcd1234'});await api('login',{username:name,password:'abcd1234'});await boot();}""",name)
    expect(page.locator('[data-page="explore"]')).to_be_visible()
    def ticks(ms):
        before=len(explore_calls)
        page.clock.run_for(ms)
        page.wait_for_timeout(500)
        return len(explore_calls)-before
    assert ticks(30500)==1 and ticks(30000)==1   # one refresh per 30 s, no duplicate timer
    page.evaluate("location.hash='#portfolio'")
    expect(page.locator('[data-page="portfolio"]').first).to_be_visible()
    assert ticks(61000)==0   # other pages do not refresh the explore list
    with page.expect_response(lambda r:'/api/explore' in r.url):
        page.evaluate("location.hash='#explore'")
    assert ticks(30000)==1
    page.locator('#logout').click()
    expect(page.locator('#auth')).to_be_visible()
    assert ticks(61000)==0   # signed out again
    page.close()
    browser.close()
print('Desktop + mobile browser flows passed: signup/login, FX, charts, buy/sell, watchlist, portfolio, profile, ranking, admin, notices, withdrawal')
