import re,time,zlib,struct
from playwright.sync_api import sync_playwright,expect

def png(width=64,height=64):
    """Left half red, right half blue, so a crop position can be checked."""
    raw=b''.join(b'\x00'+b''.join(bytes([220,30,30] if x<width//2 else [30,30,220]) for x in range(width)) for _ in range(height))
    chunk=lambda kind,data:struct.pack('>I',len(data))+kind+data+struct.pack('>I',zlib.crc32(kind+data))
    return b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',width,height,8,2,0,0,0))+chunk(b'IDAT',zlib.compress(raw))+chunk(b'IEND',b'')

with sync_playwright() as p:
    browser=p.chromium.launch(args=['--no-sandbox'])
    for width,height in [(1440,1000),(390,844)]:
        page=browser.new_page(viewport={'width':width,'height':height})
        errors=[]
        page.on('pageerror',lambda e:errors.append(str(e)))
        page.goto('http://browserweb:8000/')
        expect(page).to_have_title('VANTAGE · 모의투자')
        name='browser_'+str(width)+'_'+str(int(time.time()))
        page.locator('#showSignup').click()
        expect(page.locator('#registerForm')).to_be_visible()
        page.locator('#registerUsername').fill(name)
        page.locator('#registerPassword').fill('abcd1234')
        page.locator('#registerConfirm').fill('abcd1235')
        page.locator('#registerSubmit').click()
        expect(page.locator('#registerError')).to_have_text('비밀번호가 일치하지 않습니다.')
        page.locator('#registerConfirm').fill('abcd1234')
        page.locator('#registerSubmit').click()
        expect(page.locator('#authForm')).to_be_visible()
        expect(page.locator('#toasts')).to_contain_text('회원가입이 완료')
        expect(page.locator('#username')).to_have_value(name)
        page.locator('#password').fill('abcd1234')
        page.locator('#loginSubmit').click()
        expect(page.locator('#dashboard')).to_be_visible()
        page.locator('a[href="#portfolio"]').click()
        expect(page.locator('#metrics')).to_contain_text('100,000')
        page.locator('a[href="#fx"]').click()
        expect(page.locator('#fxRate')).to_contain_text('1 USD')
        expect(page.locator('#fxAmountUnit')).to_have_text('USD')
        expect(page.locator('#fxAvailable')).to_contain_text('100,000')
        page.locator('#fxAmount').fill('1000')
        page.locator('#fxPreview').click()
        expect(page.locator('#fxEstimate')).to_contain_text('998,500')
        page.locator('#fxForm button.full-width').click()
        expect(page.locator('#fxHistory')).to_contain_text('998,500')
        expect(page.locator('#fxAvailable')).to_contain_text('99,000')
        page.locator('#fxSource').select_option('KRW')
        expect(page.locator('#fxAmountUnit')).to_have_text('KRW')
        expect(page.locator('#fxAvailable')).to_contain_text('998,500')
        page.locator('[data-fx-share="50"]').click()
        expect(page.locator('#fxAmount')).to_have_value('499250')
        expect(page.locator('#fxEstimate')).to_contain_text('최종 수령')
        page.locator('#fxSource').select_option('USD')
        page.locator('[data-fx-share="100"]').click()
        expect(page.locator('#fxAmount')).to_have_value('99000')
        page.locator('a[href="#explore"]').click()
        expect(page.locator('#exploreMarkets button')).to_have_count(5)
        expect(page.locator('#exploreKinds button')).to_have_text(['거래량','거래대금','급상승','급하락','VANTAGE 인기'])
        expect(page.locator('[data-kind="shares"]')).to_have_attribute('aria-pressed','true')
        page.locator('[data-kind="volume"]').click()
        expect(page.locator('#exploreRows th')).to_contain_text(['#','종목','현재가','등락률','거래대금','거래량','시장'])
        expect(page.locator('#exploreRows .admin-diagnostic')).to_have_count(0)
        page.locator('[data-asset="us_bond"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('미국 국채 20년')
        page.locator('[data-asset="gold"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('SPDR Gold Shares')
        expect(page.locator('#exploreRows')).to_contain_text('ACE KRX금현물')
        expect(page.locator('#exploreRows td.gain').first).to_have_css('color','rgb(217, 75, 87)')
        expect(page.locator('#exploreRows td.loss').first).to_have_css('color','rgb(54, 122, 231)')
        page.locator('#displayCurrency').select_option('KRW')
        expect(page.locator('#exploreFxNote')).to_contain_text('기준환율')
        expect(page.locator('#exploreRows')).to_contain_text('100,000원')
        page.locator('[data-asset="kr_bond"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('Kodex 국고채3년')
        expect(page.locator('#exploreRows')).to_contain_text('억원')
        page.locator('[data-asset="kr"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('삼성전자')
        page.locator('[data-asset="us"]').click()
        expect(page.locator('[data-asset="us"]')).to_have_attribute('aria-pressed','true')
        expect(page.locator('#exploreNotice')).to_contain_text('순위가 아닙니다')
        expect(page.locator('#exploreRows')).to_contain_text('Apple')
        page.locator('[data-kind="up"]').click()
        expect(page.locator('#exploreRows')).to_contain_text('Apple')
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth+1')
        if width<600: expect(page.locator('#exploreRows .volume-cell').last).to_be_visible()
        page.screenshot(path=f'/artifacts/explore-{width}.png',full_page=True)
        page.locator('#exploreRows .stock-link').first.click()
        expect(page.locator('#detailPrice')).to_contain_text('100')
        expect(page.locator('#detailPrice .gain').first).to_have_css('color','rgb(217, 75, 87)')
        expect(page.locator('#orderType')).to_have_count(0)
        expect(page.locator('#searchResults')).to_contain_text('최근 본 종목')
        expect(page.locator('#searchResults')).to_contain_text('AAPL')
        expect(page.locator('#chartNotice')).to_contain_text('과거 가격 데이터')
        expect(page.locator('#periodPerformance')).to_contain_text('%')
        page.locator('#displayCurrency').select_option('USD')
        expect(page.locator('#displayCurrency')).to_have_value('USD')
        expect(page.locator('#detailPrice')).to_contain_text('$100')
        expect(page.locator('#periodPerformance')).to_contain_text('$100.00')
        expect(page.locator('#orderEstimate')).to_contain_text('$')
        page.locator('#displayCurrency').select_option('KRW')
        expect(page.locator('#detailPrice')).to_contain_text('100,000원')
        expect(page.locator('#periodPerformance')).to_contain_text('100,000원')
        expect(page.locator('#orderEstimate')).to_contain_text('원')
        for period in ['1D','1W','3M','1Y','5Y','ALL']:
            page.locator(f'[data-range="{period}"]').click()
            expect(page.locator('#chartNotice')).to_contain_text('과거 가격 데이터')
            expect(page.locator('#periodPerformance')).to_contain_text(period+' ·')
            expect(page.locator('#periodPerformance')).to_contain_text('5,900원')
        page.locator('#priceChart').focus();page.keyboard.press('ArrowRight')
        expect(page.locator('#chartTooltip')).to_contain_text('구간 시작 대비')
        page.locator('[data-order-share="0.05"]').click()
        expect(page.locator('#quantity')).to_have_value('49')
        expect(page.locator('#orderEstimate')).to_contain_text('수수료')
        expect(page.locator('.side-toggle [data-side="buy"]')).to_have_css('color','rgb(217, 75, 87)')
        expect(page.locator('#submitOrder')).to_have_css('background-color','rgb(217, 75, 87)')
        page.locator('#quantity').fill('2')
        page.locator('#submitOrder').click()
        expect(page.locator('#toasts')).to_contain_text('매수 주문이 체결되었습니다.')
        expect(page.locator('#toasts')).to_contain_text('Apple 2주')
        expect(page.locator('#toasts .toast').last).to_be_in_viewport()
        expect(page.locator('#orderEstimate')).to_contain_text('보유 주식2주')
        page.locator('.side-toggle [data-side="sell"]').click()
        expect(page.locator('#side')).to_have_value('sell')
        expect(page.locator('.side-toggle [data-side="sell"]')).to_have_css('color','rgb(54, 122, 231)')
        expect(page.locator('#submitOrder')).to_have_text('매도 주문')
        page.locator('[data-order-share="0.05"]').click()
        expect(page.locator('#quantity')).to_have_value('0')
        expect(page.locator('#submitOrder')).to_be_disabled()
        page.locator('[data-order-share="0.5"]').click()
        expect(page.locator('#quantity')).to_have_value('1')
        expect(page.locator('#submitOrder')).to_be_enabled()
        page.locator('#watchAdd').click()
        expect(page.locator('#toasts')).to_contain_text('관심종목')
        expect(page.locator('#companyInfo')).to_contain_text('배당률')
        page.screenshot(path=f'/artifacts/detail-{width}.png',full_page=True)
        page.locator('a[href="#watchlist"]').click()
        expect(page.locator('#watchRows .watch-name')).to_contain_text('Apple')
        expect(page.locator('#watchRows .watch-price')).to_contain_text('100,000원')
        expect(page.locator('#watchRows .watch-change .gain').first).to_have_css('color','rgb(217, 75, 87)')
        page.screenshot(path=f'/artifacts/watchlist-{width}.png',full_page=True)
        page.locator('a[href="#portfolio"]').click()
        expect(page.locator('#positions')).to_contain_text('AAPL')
        expect(page.locator('#myProfile .profile-name')).to_have_text(name)
        expect(page.locator('#myProfile .avatar')).to_have_attribute('src','/static/avatar-default.svg')
        expect(page.locator('#allocation .allocation-segment')).to_have_count(2)
        expect(page.locator('#allocation .allocation-legend')).to_contain_text('현금')
        page.locator('#displayCurrency').select_option('USD')
        expect(page.locator('#metrics')).to_contain_text('KRW: 998,500원')
        expect(page.locator('#myProfile .profile-stats')).to_contain_text('$')
        page.locator('#displayCurrency').select_option('KRW')
        expect(page.locator('#metrics')).to_contain_text('USD: $')
        for text in (page.locator('#metrics').inner_text(),page.locator('#allocation').inner_text(),page.locator('#positions').inner_text()):
            assert 'US$' not in text and '₩' not in text, text
        assert re.search(r'USD: \$[0-9,]+\.[0-9]{2}',page.locator('#metrics').inner_text()) and re.search(r'KRW: [0-9,]+원',page.locator('#metrics').inner_text())
        expect(page.locator('#myProfile .profile-stats')).to_contain_text('원')
        page.locator('#myProfile').get_by_text('소개 수정').click()
        page.locator('#bioInput').fill('장기 투자 위주로 하고 있습니다.')
        page.locator('#myProfile').get_by_text('소개 저장').click()
        expect(page.locator('#myProfile .profile-bio')).to_have_text('장기 투자 위주로 하고 있습니다.')
        page.locator('#profileImageInput').set_input_files({'name':'avatar.png','mimeType':'image/png','buffer':png(200,100)})
        expect(page.locator('#cropDialog')).to_be_visible()
        page.locator('#cropCancel').click()
        expect(page.locator('#cropDialog')).to_be_hidden()
        expect(page.locator('#myProfile .avatar')).to_have_attribute('src','/static/avatar-default.svg')
        page.locator('#profileImageInput').set_input_files({'name':'avatar.png','mimeType':'image/png','buffer':png(200,100)})
        box=page.locator('#cropCanvas').bounding_box()
        # The wide image covers the square; dragging left brings its right (blue) half into the frame.
        page.mouse.move(box['x']+box['width']*.75,box['y']+box['height']/2);page.mouse.down()
        page.mouse.move(box['x']+box['width']*.25,box['y']+box['height']/2,steps=8);page.mouse.up()
        page.locator('#cropApply').click()
        expect(page.locator('#cropDialog')).to_be_hidden()
        expect(page.locator('#myProfile .avatar')).to_have_attribute('src',f'/api/users/{name}/avatar?v=1')
        # Deleting asks first; cancel keeps the photo, confirm removes it.
        page.locator('#myProfile').get_by_text('사진 삭제').click()
        expect(page.locator('#photoDeleteDialog')).to_contain_text('프로필 사진을 삭제하시겠습니까?')
        page.locator('#photoDeleteCancel').click()
        expect(page.locator('#photoDeleteDialog')).to_be_hidden()
        expect(page.locator('#myProfile .avatar')).to_have_attribute('src',f'/api/users/{name}/avatar?v=1')
        page.locator('#myProfile').get_by_text('사진 삭제').click()
        page.keyboard.press('Escape')
        expect(page.locator('#photoDeleteDialog')).to_be_hidden()
        assert page.evaluate("api('profile').then(p=>p.image_version)")==1
        center=page.evaluate('''async url=>{const b=await createImageBitmap(await (await fetch(url)).blob());const c=document.createElement('canvas');c.width=b.width;c.height=b.height;const x=c.getContext('2d');x.drawImage(b,0,0);return [b.width,[...x.getImageData(b.width/2,b.height/2,1,1).data].slice(0,3)];}''',f'/api/users/{name}/avatar?v=1')
        assert center[0]==512 and center[1][2]>150 and center[1][0]<100, center
        # Zooming out below the frame leaves white margins around the whole photo.
        page.locator('#profileImageInput').set_input_files({'name':'avatar.png','mimeType':'image/png','buffer':png(200,100)})
        for _ in range(6): page.locator('#cropZoomOut').click()
        assert float(page.locator('#cropZoom').input_value())<.5
        # Any zoom the slider or buttons produce is valid; the form never shows a validity message.
        page.locator('#cropZoom').fill('0.4173')
        assert page.evaluate("document.getElementById('cropZoom').validity.valid && document.getElementById('cropForm').checkValidity()")
        page.locator('#cropApply').click()
        expect(page.locator('#myProfile .avatar')).to_have_attribute('src',f'/api/users/{name}/avatar?v=2')
        pixels=page.evaluate('''async url=>{const b=await createImageBitmap(await (await fetch(url)).blob());const c=document.createElement('canvas');c.width=b.width;c.height=b.height;const x=c.getContext('2d');x.drawImage(b,0,0);const at=(px,py)=>[...x.getImageData(px,py,1,1).data].slice(0,3);return {top:at(256,30),center:at(256,256)};}''',f'/api/users/{name}/avatar?v=2')
        assert min(pixels['top'])>235 and min(pixels['center'])<200, pixels
        page.locator('#myProfile').get_by_text('사진 삭제').click()
        page.locator('#photoDeleteConfirm').click()
        expect(page.locator('#photoDeleteDialog')).to_be_hidden()
        expect(page.locator('#myProfile .avatar')).to_have_attribute('src','/static/avatar-default.svg')
        expect(page.locator('#toasts')).to_contain_text('프로필 사진을 삭제했습니다.')
        page.locator('#profileImageInput').set_input_files({'name':'avatar.png','mimeType':'image/png','buffer':b'MZ not a png'})
        expect(page.locator('#toasts')).to_contain_text('올바른 이미지 파일이 아닙니다')
        expect(page.locator('#positions .portfolio-stock-link')).to_have_attribute('href','#detail/AAPL')
        page.screenshot(path=f'/artifacts/portfolio-{width}.png',full_page=True)
        page.locator('#positions .portfolio-stock-link').click()
        expect(page.locator('#detailTitle')).to_contain_text('Apple')
        page.locator('.app-nav a[href="#ranking"]').click()
        expect(page.locator('#rankingStatus')).to_contain_text('10초 단위')
        with page.expect_response(lambda r:r.url.endswith('/api/ranking'),timeout=15000):
            pass
        expect(page.locator('#ranking .user-link').first).to_have_css('font-size','18px' if width<600 else '19px')
        rows_before=page.locator('#ranking').inner_text()
        page.route('**/api/ranking',lambda route:route.fulfill(status=503,json={'detail':'test outage'}))
        page.evaluate('refreshRankingOnly()')
        expect(page.locator('#rankingStatus')).to_contain_text('마지막 정상 갱신')
        assert page.locator('#ranking').inner_text()==rows_before
        page.unroute('**/api/ranking')
        expect(page.locator('#ranking th')).to_contain_text(['순위','사용자 · 프로필 보기','총 평가금액 (KRW)','누적 수익률'])
        expect(page.locator('#ranking td').nth(2)).to_contain_text('원')
        page.locator('#displayCurrency').select_option('USD')
        expect(page.locator('#ranking th').nth(2)).to_have_text('총 평가금액 (USD)')
        expect(page.locator('#ranking td').nth(2)).to_contain_text('$')
        page.locator('#displayCurrency').select_option('KRW')
        other=page.locator('#ranking .user-link').filter(has_not_text=name).first
        other_name=other.inner_text()
        other.click()
        expect(page.locator('#publicTitle')).to_contain_text(other_name+'님의 투자 현황')
        expect(page.locator('#publicProfile .profile-name')).to_have_text(other_name)
        expect(page.locator('#publicProfile')).not_to_contain_text('소개 수정')
        expect(page.locator('#publicProfile')).not_to_contain_text('사진 변경')
        expect(page.locator('#publicAllocation .allocation-legend')).to_be_visible()
        page.locator('a[href="#transfer"]').click()
        expect(page.locator('#transferUSD')).to_contain_text('$')
        page.locator('#transferRecipient').fill(other_name)
        page.locator('[data-transfer-share="10"]').click()
        expect(page.locator('#transferEstimate')).to_contain_text('총 차감 금액')
        expect(page.locator('#transferSubmit')).to_be_enabled()
        page.locator('#transferSubmit').click()
        expect(page.locator('#toasts')).to_contain_text('보냈습니다')
        expect(page.locator('#transferHistory')).to_contain_text(other_name)
        # Every page follows one amount format: "$1,000.00" and "1,000원".
        for display in ('native','KRW','USD'):
            page.locator('#displayCurrency').select_option(display)
            for hash_ in ('#explore','#portfolio','#history','#fx','#transfer','#watchlist','#ranking','#detail/AAPL'):
                page.goto('http://browserweb:8000/'+hash_);page.wait_for_load_state('networkidle')
                text=page.locator('main').inner_text()
                assert 'US$' not in text and '₩' not in text, (display,hash_,[l for l in text.splitlines() if 'US$' in l or '₩' in l][:3])
        page.locator('#displayCurrency').select_option('KRW')
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth+1'), 'page overflows viewport'
        assert not errors,errors
        page.close()
    page=browser.new_page(viewport={'width':390,'height':844})
    page.goto('http://browserweb:8000/')
    page.locator('#username').fill('browser_admin')
    page.locator('#password').fill('browser-fixture-password')
    page.locator('#loginSubmit').click()
    expect(page.locator('#adminNav')).to_be_visible()
    expect(page.locator('[data-page="admin"]')).to_be_visible()
    expect(page.locator('#adminOverview')).to_contain_text('사용자')
    expect(page.locator('.app-nav a:visible')).to_have_count(1)
    page.locator('#adminTargetSearch').fill(name)
    expect(page.locator('.admin-result')).to_have_count(1)
    page.locator('.admin-result').click()
    page.locator('#adminNote').fill('홍길동 / 컴공 동기')
    page.locator('#adminNoteForm button').click()
    expect(page.locator('#toasts')).to_contain_text('메모를 저장했습니다')
    page.locator('#adminTargetSearch').fill('컴공')
    expect(page.locator('.admin-result')).to_contain_text(name)
    page.locator('.admin-result').first.click()
    page.locator('[data-admin-action="rebase"]').click()
    expect(page.locator('#adminResult')).to_contain_text('수익률 기준을 현재 평가금액으로 재설정했습니다.')
    page.locator('[data-admin-action="clear"]').click()
    expect(page.locator('#adminResult')).to_contain_text('회원가입 직후 상태로 초기화했습니다.')
    page.locator('#adminAmount').fill('500')
    page.locator('#adminGrantForm button').click()
    expect(page.locator('#adminResult')).to_contain_text('지원금을 지급했습니다.')
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth+1')
    page.screenshot(path='/artifacts/explore-admin-390.png',full_page=True)
    # Maintenance notice: admin toggles it; users see a banner and keep trading.
    user=browser.new_page(viewport={'width':390,'height':844})
    user.goto('http://browserweb:8000/')
    user.locator('#showSignup').click()
    user.locator('#registerUsername').fill(name+'_n'); user.locator('#registerPassword').fill('abcd1234'); user.locator('#registerConfirm').fill('abcd1234')
    user.locator('#registerSubmit').click()
    user.locator('#password').fill('abcd1234'); user.locator('#loginSubmit').click()
    expect(user.locator('#dashboard')).to_be_visible()
    expect(user.locator('#maintenanceNotice')).to_be_hidden()
    page.locator('#maintenanceToggle').click()
    expect(page.locator('#maintenanceToggle')).to_have_text('점검 예고 해제')
    expect(page.locator('#maintenanceNotice')).to_be_hidden()
    user.evaluate('refreshNotice()')
    expect(user.locator('#maintenanceNotice')).to_be_visible()
    expect(user.locator('#maintenanceNotice')).to_contain_text('서버 점검이 예정되어 있습니다')
    expect(user.locator('#maintenanceNotice')).to_be_in_viewport()
    assert user.evaluate("api('orders',{symbol:'AAPL',side:'buy',quantity:1,request_id:uuid()}).then(r=>r.quantity)")==1
    page.locator('#maintenanceToggle').click()
    expect(page.locator('#maintenanceToggle')).to_have_text('점검 예고 등록')
    user.evaluate('refreshNotice()')
    expect(user.locator('#maintenanceNotice')).to_be_hidden()
    user.close()
    page.locator('[data-admin-action="delete"]').click()
    expect(page.locator('#adminResult')).to_contain_text('계정을 영구 삭제했습니다.')
    page.close()
    # Self-service withdrawal for the other fixture account.
    page=browser.new_page(viewport={'width':390,'height':844})
    page.goto('http://browserweb:8000/')
    page.locator('#showSignup').click()
    page.locator('#registerUsername').fill(name+'_x'); page.locator('#registerPassword').fill('abcd1234'); page.locator('#registerConfirm').fill('abcd1234')
    page.locator('#registerSubmit').click()
    page.locator('#password').fill('abcd1234'); page.locator('#loginSubmit').click()
    page.locator('a[href="#portfolio"]').click()
    page.locator('#withdrawOpen').click()
    expect(page.locator('#withdrawDialog')).to_contain_text('정말 회원 탈퇴하시겠습니까?')
    page.locator('#withdrawCancel').click()
    expect(page.locator('#withdrawDialog')).to_be_hidden()
    page.locator('#withdrawOpen').click()
    page.locator('#withdrawPassword').fill('wrong-password'); page.locator('#withdrawConfirm').click()
    expect(page.locator('#withdrawError')).to_have_text('비밀번호가 올바르지 않습니다.')
    page.locator('#withdrawPassword').fill('abcd1234'); page.locator('#withdrawConfirm').click()
    expect(page.locator('#authForm')).to_be_visible()
    expect(page.locator('#toasts')).to_contain_text('회원 탈퇴가 완료')
    assert page.evaluate("fetch('/api/portfolio').then(r=>r.status)")==401
    page.locator('#username').fill(name+'_x'); page.locator('#password').fill('abcd1234'); page.locator('#loginSubmit').click()
    expect(page.locator('#status')).to_contain_text('올바르지 않습니다')
    page.close()
    # Many holdings: every one gets its own segment; a missing price shows as pending, then fills in.
    page=browser.new_page(viewport={'width':1280,'height':900})
    page.goto('http://browserweb:8000/')
    page.locator('#showSignup').click()
    page.locator('#registerUsername').fill(name+'_many'); page.locator('#registerPassword').fill('abcd1234'); page.locator('#registerConfirm').fill('abcd1234')
    page.locator('#registerSubmit').click()
    page.locator('#password').fill('abcd1234'); page.locator('#loginSubmit').click()
    expect(page.locator('#dashboard')).to_be_visible()
    symbols=['AAPL','MSFT','NVDA','QQQ','VOO','IAU','MU','RKLB']
    page.evaluate('''async symbols=>{for(const [i,symbol] of symbols.entries())await api('orders',{symbol,side:'buy',quantity:i+1,request_id:uuid()});}''',symbols)
    state={'first':True}
    def first_without_price(route):
        response=route.fetch();data=response.json()
        if state['first']:
            state['first']=False
            for row in data['positions']:
                if row['symbol']=='MSFT':row['value']=None;row['pnl']=None;row['return_pct']=None
            data['equity']=None;data['errors']=['MSFT: 시세 수집기가 가격을 준비 중입니다. 잠시 후 다시 시도하세요.']
        route.fulfill(response=response,json=data)
    page.route('**/api/portfolio',first_without_price)
    page.evaluate('refresh()')
    page.locator('a[href="#portfolio"]').click()
    expect(page.locator('#allocation .allocation-legend li.pending')).to_contain_text('시세 준비 중')
    expect(page.locator('#allocation .allocation-segment')).to_have_count(8)
    expect(page.locator('#allocation .allocation-segment')).to_have_count(9,timeout=10000)
    expect(page.locator('#allocation .allocation-legend li')).to_have_count(9)
    expect(page.locator('#allocation .allocation-legend li.pending')).to_have_count(0)
    legend=page.locator('#allocation .allocation-legend').inner_text()
    assert '기타' not in legend and all(n in legend for n in ['Apple','현금']), legend
    page.screenshot(path='/artifacts/allocation-many-1280.png',full_page=True)
    page.close()
    browser.close()
print('Desktop + mobile browser flows passed: signup/login, FX, charts, buy/sell, watchlist, portfolio, profile, ranking, transfer, admin, withdrawal')
